- user: JenkinsDevTeamUser
  pass: JenkinsDevTeamPass
  url: http:/jenkins.devteam.com
  port: 8080
  project: DevTeam
  crumb:
  timeout: 10
- user: JenkinsProjectUser
  pass: JenkinsProjectPass
  url: http:/jenkins.projectteam.com
  port: 8080
  project: Project
  crumb:
  timeout: 10
